# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nkxm_rfZbj5K72QxYXkVElXBnubQfFPx
"""

print('Hello World')